# Site settings
title:       FlectraHQ
email:       flectra@flectrahq.com
author:      FlectraHQ
description: "Fork of Odoo"
baseurl:     ""
url:         "http://flectrahq.com"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social icons
github_username: "flectrahq"
twitter_username: "flectrahq"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
